### ISSUE TITLE
arcolinux_repo_iso (invalid or corrupted database (PGP signature)

### ISSUE THREAD

**Issue by ghost** [arcolinux/arcolinuxd-iso#4]
When i run the script to build the iso i have this error.

abdias@river installation-scripts $ ./30-build-the-iso-local.sh 

error: arcolinux_repo: key "74F5DE85A506BF64" is unknown
:: Import PGP key 2048R/93D1CCB2B2421F4B1CD0489774F5DE85A506BF64, "Erik Dubois <erik.dubois@gmail.com>", created: 2017-09-12? [Y/n] 
error: arcolinux_repo: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust
error: failed to update arcolinux_repo (invalid or corrupted database (PGP signature))
 arcolinux_repo_iso             41.8 KiB   836K/s 00:00 [------------------------------] 100%
 arcolinux_repo_iso.sig        310.0   B  0.00B/s 00:00 [------------------------------] 100%
error: arcolinux_repo_iso: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust
error: failed to update arcolinux_repo_iso (invalid or corrupted database (PGP signature))
error: database 'arcolinux_repo' is not valid (invalid or corrupted database (PGP signature))
error: database 'arcolinux_repo_iso' is not valid (invalid or corrupted database (PGP signature))

![archlabs_2018-04-23-00_1366x768](https://user-images.githubusercontent.com/13319563/39139349-4d0dac9a-46e7-11e8-97b4-8af5513ee25a.png)

i modified the **pacman.conf**

```
[arcolinux_repo]
#SigLevel = Required DatabaseOptional
SigLevel = Optional TrustAll
Server = https://arcolinux.github.io/arcolinux_repo/$arch

[arcolinux_repo_iso]
#SigLevel = Required DatabaseOptional
SigLevel = Optional TrustAll
Server = https://arcolinux.github.io/arcolinux_repo_iso/$arch
```

**Comment by arcolinuxz** [comment]
check again - everything should work
if a github is being changed - like yesterday - we updated ALL packages, it can take a while before these messages disappear

**Comment by arcolinuxz** [comment]
You should add the #SigLevel - no hashtag in front of this

**Comment by hamdi411** [comment]
I also had the same thing 
error : arcolinux_repo : key "79B328FBCB2C2E8C3B1983244B1B49F7186D8731"
:: Improt PGP key 79B328FBCB2C2E8C3B1983244B1B49F7186D8731? [Y/N]

Is there any solution ..!

**Comment by arcolinuxz** [comment]
yes it solved 

try again

**Comment by arcolinuxz** [comment]
Read this 

https://arcolinuxforum.com/viewtopic.php?f=79&t=2214

**Comment by hamdi411** [comment]
Yeah
It works now
thanks YOU brother

**Comment by IcyTv** [comment]
Since the link seems to be dead, you can fix this, by running
```bash
pacman-key --populate
```

**Comment by arcolinuxz** [comment]
forum is no more
https://arcolinuxforum.com/
