### ISSUE TITLE
Script stops after Removing old files/folders from /etc/skel output

### ISSUE THREAD

**Issue by mfurkin** [arcolinux/arcolinuxd-iso#5]
Actions sequence
1. git clone arco-xfce as it was described in your instruction
2. cd /~/Downloads/arco-xfce/installation-scripts
3. sudo sh 30-build-the-iso-local-v1.sh
Script begins, makes output as follows and stops after "Removing old files/folders from /etc/skel output". Script output:
################################################################## 
Phase 1 : clean up and download the latest ArcoLinux-iso from github
################################################################## 

Deleting the work folder if one exists
Deleting the build folder if one exists - takes some time
Git cloning files and folder to work folder
Клонирование в «../work»…
remote: Counting objects: 957, done.
remote: Compressing objects: 100% (72/72), done.
Получение объектов: 100% (957/957), 4.06 MiB | 398.00 KiB/s, готово.
remote: Total 957 (delta 53), reused 78 (delta 32), pack-reused 849
Определение изменений: 100% (553/553), готово.

################################################################## 
Phase 2 : Getting the latest versions for some important files
################################################################## 

Removing the old packages.x86_64 file from work folder
Copying the new packages.x86_64 file
Removing old files/folders from /etc/skel

May be, I did something wrong. Would you please help me?

Thanks in advance,
Mikhail

**Comment by arcolinuxz** [comment]
You are mixing arco-xfce and arcolinux-iso and arcolinuxd-iso together.

Follow the tutorials to the letter 

https://arcolinuxd.com/category/arcolinuxb/byoi/
