### ISSUE TITLE
Some sugesstion for netinstall 

### ISSUE THREAD

**Issue by ThavaNix** [arcolinux/arcolinuxd-iso#6]
- open-vm-tools 
- kdebase-meta(minimal version of kde-apps) for kde plasama

**Comment by arcolinuxz** [comment]
Open-vm-tools is in next time
kdebase-meta is in next time

**Comment by arcolinuxz** [comment]
@ThavaNix Can you build the ArcoLinuxD iso with this tutorial https://arcolinuxb.com/byoi-on-arcolinuxd-no-changes-made/ and give us feedback about the open-vm-tools. We support Virtual Box.

**Comment by ThavaNix** [comment]
But open-vm-tools in not on the netinstall list?

**Comment by arcolinuxz** [comment]
It is now IF you build it yourself

**Comment by ThavaNix** [comment]
I build it yes thats but is not enabled at starts open-vm-tools

**Comment by arcolinuxz** [comment]
If we enable it ... it will probably clash with virtualbox which is enabled
that is something the user will have to do
