### ISSUE TITLE
error: arcolinux_repo: signature from "Erik Dubois <erik.dubois@gmail.com>" is unknown trust

### ISSUE THREAD

**Issue by ggichuru** [arcolinux/arcolinuxd-iso#8]
Getting this error when trying to run Pacman on arcolinux
![ArcoLinux_2022-01-22_11-17-07](https://user-images.githubusercontent.com/66542320/150630720-585bcc31-edd1-4640-b2e0-57d63cb85983.png)

**Comment by arcolinuxz** [comment]
type "fixkey" in a terminal and solved
